/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Home: typeof import('./src/views/Home/index.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanSearch: typeof import('vant/es')['Search']
  }
}
